<div style="text-align: center;">
    <img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" alt="Numpy Logo" width="500">
    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/1280px-Pandas_logo.svg.png" alt="Pandas Logo" width="500">
    <p style="font-size: 50px; font-weight: bold;">Pengenalan NumPy dan Pandas pada Python</p>
    <p style="font-size: 50px; font-weight: normal;"> Intern BCC 2024</p>
</div>


# Numpy 🧮


**NumPy** atau Numerical Python adalah sebuah library Python yang menyediakan struktur data dan fungsi-fungsi untuk bekerja dengan array dan matriks multidimensi. **NumPy** meningkatkan efisiensi dalam melakukan operasi dan manipulasi data dengan ukuran yang besar


In [1]:
import numpy as np

### Membuat Array Numpy


In [72]:
arr1d = np.array([1,2,3])

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Menampilkan informasi tentang array 2D


In [3]:
print("Dimensi Array 2D:", arr2d.ndim)
print("Ukuran Array 2D:", arr2d.shape)
print("Jumlah elemen Array 2D:", arr2d.size)
print("Tipe Data Array 2D:", arr2d.dtype)

Dimensi Array 2D: 2
Ukuran Array 2D: (3, 3)
Jumlah elemen Array 2D: 9
Tipe Data Array 2D: int32


### Slicing dan Indexing Array


In [75]:
print("Element index ke-1 arr1d\t\t:", arr1d[1])
print("Element index ke-1 hingga 2 arr1d\t:", arr1d[1:3])

print("Element baris ke-1 dan kolom ke-2\t:", arr2d[0:2, 0])

Element index ke-1 arr1d		: 2
Element index ke-1 hingga 2 arr1d	: [2 3]
Element baris ke-1 dan kolom ke-2	: [1 4]


### Menghitung Statistik


In [78]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Menghitung statistik
mean_value = np.mean(arr2d, axis=0)
median_value = np.median(arr2d)
std_deviation = np.std(arr2d)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)

Mean: [4. 5. 6.]
Median: 5.0
Standard Deviation: 2.581988897471611


### Aritmatika


In [82]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])


# Operasi Transposisi
transposed_arr = arr1.T
transposed_arr = np.transpose(arr1)
print("Transposed Array arr1:\n", transposed_arr)

# Operasi dot product
dot_product = np.dot(arr1, arr2)
dot_product = arr1.dot(arr2)
print("Dot Product:\n", dot_product)


# Operasi penjumlahan
# sum_arr = arr1 + arr2
sum_arr = np.add(arr1, arr2)
print("Penjumlahan:\n", sum_arr)

Transposed Array arr1:
 [[1 3]
 [2 4]]
Dot Product:
 [[19 22]
 [43 50]]
Penjumlahan:
 [[ 6  8]
 [10 12]]


### Reshaping Array

**Reshape** adalah metode dalam NumPy yang digunakan untuk mengubah bentuk (shape/dimensi) dari sebuah array NumPy tanpa mengubah isi datanya.


In [7]:
# Membuat array 1D dengan 9 elemen menggunakan method arrange
# 0, 1, 2, 3, 4, 5, 6, 7, 8

arr1d = np.arange(start=0, step=1, stop=9)
print("Array 1D:")
print(arr1d)

# Mengubah array 1D menjadi matriks 3x3
arr2d_3x3 = arr1d.reshape(3, 3)
print("Matriks 3x3:")
print(arr2d_3x3)

# Mengubah array 1D menjadi vektor baris 1x9
arr2d_row = arr1d.reshape(1, 9)
print("Vektor Baris 1x9:")
print(arr2d_row)

# Mengubah array 1D menjadi vektor kolom 9x1
arr2d_col = arr1d.reshape(9, 1)
print("Vektor Kolom 9x1:")
print(arr2d_col)

Array 1D:
[0 1 2 3 4 5 6 7 8]
Matriks 3x3:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Vektor Baris 1x9:
[[0 1 2 3 4 5 6 7 8]]
Vektor Kolom 9x1:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


# Pandas 🐼

**Pandas** adalah sebuah library Python yang digunakan untuk manipulasi dan analisis data. **Pandas** menyediakan struktur data yang fleksibel dan kaya akan fitur untuk mengolah data tabular, seperti data yang ada pada file CSV atau spreadsheet. Library ini sangat berguna untuk mempersiapkan data untuk analisis dan pemodelan statistik. Pandas juga memiliki banyak fungsi untuk melakukan operasi matematika dan statistik.


## Import Pandas


In [84]:
!pip install pandas

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [8]:
import pandas as pd
print(pd)

<module 'pandas' from 'c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pandas\\__init__.py'>


## Read CSV

Pandas dapat membaca file dengan format file csv ataupun excel lalu dikonversi ke tipe data DataFrame.


In [9]:
# Download dataset ke dalam direktori lokal, tanpa dikonversi ke DataFrame

!wget https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [85]:
# Mengambil dari file path lokal
data = pd.read_csv("./titanic.csv")

# Mengambil dari GitHub
data = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

# Mengambil dari Google Drive ( drive.google.com/file/d/1cxttBfHGltz1enyM_BQYiedU73t5mKMX/view?usp=drive_link )
id = "1cxttBfHGltz1enyM_BQYiedU73t5mKMX"
data = pd.read_csv("https://drive.google.com/uc?id=" + id, delimiter=',')

print(type(data))

<class 'pandas.core.frame.DataFrame'>


## DataFrame

DataFrame pada Pandas adalah sebuah struktur data dua dimensi yang mirip dengan tabel terdiri dari baris dan kolom.

Komponen pada DataFrame:

1. Data, Nilai-nilai yang disimpan di dalam DataFrame dengan tipe data yang dapat beragam
2. Index, Label unik pada setiap baris pada DataFrame
3. Columns Names, Label atau identifikasi terhadap data yang disimpan dalam suatu kolom
4. Data Types, Tipe data dari setiap kolom pada DataFrame


In [11]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

### Membuat DataFrame Secara Manual

Untuk memahami lebih lanjut, DataFrame juga dapat dibuat dengan menggunakan bantuan struktur data **Dictionary** pada Python.

- **Key** interpretasi dari label kolom dengan tipe data string
- **Value** interpretasi dari data pada suatu kolom dengan tipe data list
- Label index secara otomatis dibuat dari 0 hingga n


In [87]:
dict_data = {
    'Nama': ['Evan', 'Firhan', 'Byu', 'Mira'],
    'Jenis Kelamin': ['L', 'L', 'L', 'P'],
    'Tempat Tinggal': ['Banyuwangi', 'Bandung', 'Malang', 'Malang'],
    'Umur': [20, 21, 20, 21]
}

manual_df = pd.DataFrame(dict_data)
manual_df

Nama Jenis Kelamin Tempat Tinggal  Umur
0    Evan             L     Banyuwangi    20
1  Firhan             L        Bandung    21
2     Byu             L         Malang    20
3    Mira             P         Malang    21

### Modifikasi Komponen pada DataFrame


In [88]:
# Mengubah label kolom pada DataFrame
# manual_df = manual_df.rename(columns={'Nama': 'Name', 'Jenis Kelamin': 'Gender', 'Tempat Tinggal': 'Address', 'Umur': 'Age'})
manual_df.rename(columns={'Nama': 'Name', 'Jenis Kelamin': 'Gender', 'Tempat Tinggal': 'Address', 'Umur': 'Age'}, inplace=True)

# Mengubah label indeks/baris pada DataFrame
manual_df.rename(index={2: 'index baru'}, inplace=True)

manual_df

Name Gender     Address  Age
0             Evan      L  Banyuwangi   20
1           Firhan      L     Bandung   21
index baru     Byu      L      Malang   20
3             Mira      P      Malang   21

#### Menambah Kolom dan Baris pada Dataframe


In [90]:
# Menambah Kolom Status pada manual_df
# manual_df['Status'] = 'Single'
manual_df['Status'] = ['Single', 'Double', 'Single', 'Double']
manual_df

Name Gender     Address  Age  Status
0             Evan      L  Banyuwangi   20  Single
1           Firhan      L     Bandung   21  Double
index baru     Byu      L      Malang   20  Single
3             Mira      P      Malang   21  Double

In [91]:
print(len(manual_df))

4


In [93]:
# Menambah Baris baru pada manual_df
manual_df.loc[len(manual_df)] = ['Jeki', 'L', 'Jakarta', 20, 'Single']
manual_df

Name Gender     Address  Age  Status
0             Evan      L  Banyuwangi   20  Single
1           Firhan      L     Bandung   21  Double
index baru     Byu      L      Malang   20  Single
3             Jeki      L     Jakarta   20  Single
4             Jeki      L     Jakarta   20  Single

In [95]:
manual_df['Copy Name'] = manual_df['Name']
manual_df

Name Gender     Address  Age  Status Copy Name
0             Evan      L  Banyuwangi   20  Single      Evan
1           Firhan      L     Bandung   21  Double    Firhan
index baru     Byu      L      Malang   20  Single       Byu
3             Jeki      L     Jakarta   20  Single      Jeki
4             Jeki      L     Jakarta   20  Single      Jeki

## Series

Series dalam Pandas adalah struktur data satu dimensi yang mirip dengan array atau kolom dalam tabel. Series dapat menyimpan data dari berbagai tipe, seperti integer, float, string, atau objek Python. Satu hal yang membedakan Series dari array sederhana adalah adanya indeks yang menyertai setiap elemen dalam Series.

Komponen pada Series:

1. Data, Nilai-nilai yang disimpan dalam Series yang dapat berupa berbagai jenis tipe data.
2. Index, Label unik pada setiap elemen pada Series, secara default akan diberikan index label dari 0 hingga n.


In [16]:
# Mengambil Series dari kolom Age pada Dataframe data
age_series = data["Age"]

print("Tipe data:", type(age_series))

age_series

Tipe data: <class 'pandas.core.series.Series'>


0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

### Membuat Series Secara Manual

Untuk memahami lebih lanjut, Series juga dapat dibuat dengan menggunakan bantuan struktur data **List** pada Python.


In [96]:
list_data = ['Evan', 'Firhan', 'Bayu', 'Mira']
manual_series = pd.Series(list_data)
manual_series

0      Evan
1    Firhan
2      Bayu
3      Mira
dtype: object

## Data Exploration Using Pandas


### Head

Mendapatkan baris n teratas pada data, default n = 5


In [97]:
data.head(20)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S  
15      0            248706  16.0000   NaN        S  
16      1            382652  29.1250   NaN        Q  
17      0            244373  13.0000   NaN        S  
18      0            345763  18.0000   NaN        S  
19      0              2649   7.2250   NaN        C

### Tail

Mendapatkan baris n terbawah pada data, default n = 5


In [101]:
data.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [104]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

### Shape

Mengembalikan sebuah _tuple_ yang berisi $(n, m)$

$n$ = Jumlah baris pada data

$m$ = Jumlah kolom pada data


In [103]:
data.shape

(891, 12)

### Info

Mendapatkan informasi detail dari setiap **kolom** pada data


In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


### Ringkasan Statistik

Mendapatkan ringkasan statistik pada kolom-kolom **numerik**

1. count = Jumlah baris
2. mean = Rata-rata nilai
3. std = Standar Deviasi
4. min = Nilai paling kecil
5. 25% = Presentil bawah
6. 50% = Median
7. 75% = Presentil atas
8. max = Nilai paling besar


In [22]:
# Menggunakan Describe
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [105]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [107]:
# Perkolom satu-persatu 
print("Rata-rata umur: ", data['Age'].median())
print("Jumlah Keseluruhan Penumpang:", data['PassengerId'].count())

Rata-rata umur:  28.0
Jumlah Keseluruhan Penumpang: 891


### Melihat Nilai Unik


In [108]:
data["Sex"].unique()

array(['male', 'female'], dtype=object)

### Melihat Jumlah Nilai Unik


In [109]:
data["Sex"].nunique()

2

### Melihat Jumlah Data untuk Setiap Nilai Unik


In [110]:
data["Sex"].value_counts()

male      577
female    314
Name: Sex, dtype: int64

### Seleksi

Mendapatkan nilai pada baris atau kolom tertentu pada DataFrame


#### Seleksi menggunakan [ ]

Indexing paling sederhana untuk mengambil data pada suatu kolom namun tidak bisa mengambil pada baris tertentu.

**data[columns_name]**


In [114]:
# Mengambil semua data pada sebuah kolom tertentu dalam bentuk DataFrame
data["Sex"]

0        male
1      female
2      female
3      female
4        male
        ...  
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [27]:
# Mengambil semua data pada sebuah kolom tertentu dalam bentuk Series
data["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [28]:
# Mengambil semua data pada kolom tertentu
data[["Name", "Sex", "Age"]]

Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
886                              Montvila, Rev. Juozas    male  27.0
887                       Graham, Miss. Margaret Edith  female  19.0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889                              Behr, Mr. Karl Howell    male  26.0
890                                Dooley, Mr. Patrick    male  32.0

[891 rows x 3 columns]

#### Seleksi Menggunakan loc

Indexing menggunakan **label/nama** baris dan kolom

**data.loc[row_label, column_label]**


In [116]:
# Mengambil baris index 0 hingga 5 pada semua kolom
data.loc[0:5]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q

In [30]:
# Mengambil semua baris pada kolom tertentu
data.loc[:, ["Name", "Cabin"]]

Name Cabin
0                              Braund, Mr. Owen Harris   NaN
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   C85
2                               Heikkinen, Miss. Laina   NaN
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  C123
4                             Allen, Mr. William Henry   NaN
..                                                 ...   ...
886                              Montvila, Rev. Juozas   NaN
887                       Graham, Miss. Margaret Edith   B42
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  C148
890                                Dooley, Mr. Patrick   NaN

[891 rows x 2 columns]

In [31]:
# Mengambil range index baris ternetu pada kolom tertentu menggunakan list
data.loc[887:891, ["Name", "Age"]]

Name   Age
887              Graham, Miss. Margaret Edith  19.0
888  Johnston, Miss. Catherine Helen "Carrie"   NaN
889                     Behr, Mr. Karl Howell  26.0
890                       Dooley, Mr. Patrick  32.0

In [117]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [32]:
# Mengambil range index baris ternetu pada range kolom tertentu
data.loc[0:5, "Name":"Age"]

Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
5                                   Moran, Mr. James    male   NaN

In [33]:
# Mengambil baris index tertentu dan pada kolom tertentu menggunakan list
data.loc[[1, 5, 881, 886], ['Name', 'Age']]

Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
5                                     Moran, Mr. James   NaN
881                                 Markun, Mr. Johann  33.0
886                              Montvila, Rev. Juozas  27.0

#### Seleksi Menggunakan iloc

Indexing menggunakan **index integer**, cara penggunaan mirip dengan loc namun menggunakan index integer

**data.iloc[row_index, column_index]**


In [118]:
# Mengambil range baris tertentu pada range kolom tertentu
data.iloc[1:5, 0:4]

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  
2                             Heikkinen, Miss. Laina  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  
4                           Allen, Mr. William Henry

In [35]:
# Mengambil semua baris pada kolom tertentu
data.iloc[:, [0, 5]]

PassengerId   Age
0              1  22.0
1              2  38.0
2              3  26.0
3              4  35.0
4              5  35.0
..           ...   ...
886          887  27.0
887          888  19.0
888          889   NaN
889          890  26.0
890          891  32.0

[891 rows x 2 columns]

#### Seleksi Index Boolean

.loc dan [ ] dapat digunakan sebagai **Boolean Indexing**


In [119]:
data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [121]:
data['Age'] < 5

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [122]:
data[(data['Sex'] == 'male')]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
889          890         1       1           Behr, Mr. Karl Howell  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
889  26.0      0      0            111369  30.0000  C148        C  
890  32.0      0      0            370376   7.7500   NaN        Q  

[577 rows x 12 columns]

In [36]:
# Mengembalikan hasil operasi boolean dalam bentuk struktur data 1 dimensi
filter_umur_balita = data["Age"] < 5
filter_umur_balita

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [37]:
# Mengembalikan baris data yang bernilai True atau memenuhi kondisi kolom Age < 5 (Balita)
data[filter_umur_balita]

PassengerId  Survived  Pclass                                      Name  \
7              8         0       3            Palsson, Master. Gosta Leonard   
10            11         1       3           Sandstrom, Miss. Marguerite Rut   
16            17         0       3                      Rice, Master. Eugene   
43            44         1       2  Laroche, Miss. Simonne Marie Anne Andree   
63            64         0       3                     Skoog, Master. Harald   
78            79         1       2             Caldwell, Master. Alden Gates   
119          120         0       3         Andersson, Miss. Ellis Anna Maria   
164          165         0       3              Panula, Master. Eino Viljami   
171          172         0       3                      Rice, Master. Arthur   
172          173         1       3              Johnson, Miss. Eleanor Ileen   
183          184         1       2                 Becker, Master. Richard F   
184          185         1       3       Kink-Heilmann, Miss. Luise Gretchen   
193          194         1       2                Navratil, Master. Michel M   
205          206         0       3                Strom, Miss. Telma Matilda   
261          262         1       3         Asplund, Master. Edvin Rojj Felix   
297          298         0       1              Allison, Miss. Helen Loraine   
305          306         1       1            Allison, Master. Hudson Trevor   
340          341         1       2            Navratil, Master. Edmond Roger   
348          349         1       3    Coutts, Master. William Loch "William"   
374          375         0       3                Palsson, Miss. Stina Viola   
381          382         1       3               Nakid, Miss. Maria ("Mary")   
386          387         0       3           Goodwin, Master. Sidney Leonard   
407          408         1       2            Richards, Master. William Rowe   
445          446         1       1                 Dodge, Master. Washington   
469          470         1       3             Baclini, Miss. Helene Barbara   
479          480         1       3                  Hirvonen, Miss. Hildur E   
530          531         1       2                  Quick, Miss. Phyllis May   
618          619         1       2               Becker, Miss. Marion Louise   
642          643         0       3             Skoog, Miss. Margit Elizabeth   
644          645         1       3                    Baclini, Miss. Eugenie   
691          692         1       3                        Karun, Miss. Manca   
750          751         1       2                         Wells, Miss. Joan   
755          756         1       2                 Hamalainen, Master. Viljo   
788          789         1       3                Dean, Master. Bertram Vere   
803          804         1       3           Thomas, Master. Assad Alexander   
824          825         0       3              Panula, Master. Urho Abraham   
827          828         1       2                     Mallet, Master. Andre   
831          832         1       2           Richards, Master. George Sibley   
850          851         0       3   Andersson, Master. Sigvard Harald Elias   
869          870         1       3           Johnson, Master. Harold Theodor   

        Sex   Age  SibSp  Parch           Ticket      Fare    Cabin Embarked  
7      male  2.00      3      1           349909   21.0750      NaN        S  
10   female  4.00      1      1          PP 9549   16.7000       G6        S  
16     male  2.00      4      1           382652   29.1250      NaN        Q  
43   female  3.00      1      2    SC/Paris 2123   41.5792      NaN        C  
63     male  4.00      3      2           347088   27.9000      NaN        S  
78     male  0.83      0      2           248738   29.0000      NaN        S  
119  female  2.00      4      2           347082   31.2750      NaN        S  
164    male  1.00      4      1          3101295   39.6875      NaN        S  
171    male  

In [123]:
# Menampilkan baris data dengan Age < 5 dan Survived == 0
filter_balita = data["Age"] < 5
filter_meninggoy = data["Survived"] == 0

data[filter_balita & filter_meninggoy]

PassengerId  Survived  Pclass                                     Name  \
7              8         0       3           Palsson, Master. Gosta Leonard   
16            17         0       3                     Rice, Master. Eugene   
63            64         0       3                    Skoog, Master. Harald   
119          120         0       3        Andersson, Miss. Ellis Anna Maria   
164          165         0       3             Panula, Master. Eino Viljami   
171          172         0       3                     Rice, Master. Arthur   
205          206         0       3               Strom, Miss. Telma Matilda   
297          298         0       1             Allison, Miss. Helen Loraine   
374          375         0       3               Palsson, Miss. Stina Viola   
386          387         0       3          Goodwin, Master. Sidney Leonard   
642          643         0       3            Skoog, Miss. Margit Elizabeth   
824          825         0       3             Panula, Master. Urho Abraham   
850          851         0       3  Andersson, Master. Sigvard Harald Elias   

        Sex  Age  SibSp  Parch   Ticket      Fare    Cabin Embarked  
7      male  2.0      3      1   349909   21.0750      NaN        S  
16     male  2.0      4      1   382652   29.1250      NaN        Q  
63     male  4.0      3      2   347088   27.9000      NaN        S  
119  female  2.0      4      2   347082   31.2750      NaN        S  
164    male  1.0      4      1  3101295   39.6875      NaN        S  
171    male  4.0      4      1   382652   29.1250      NaN        Q  
205  female  2.0      0      1   347054   10.4625       G6        S  
297  female  2.0      1      2   113781  151.5500  C22 C26        S  
374  female  3.0      3      1   349909   21.0750      NaN        S  
386    male  1.0      5      2  CA 2144   46.9000      NaN        S  
642  female  2.0      3      2   347088   27.9000      NaN        S  
824    male  2.0      4      1  3101295   39.6875      NaN        S  
850    male  4.0      4      2   347082   31.2750      NaN        S

In [129]:
data[(data["Age"] < 5) & (data["Survived"] == 0)].shape[0]

13

In [130]:
# Menampilkan baris data dengan Age < 5 atau Survived == 0
data[(data["Age"] < 5) | (data["Survived"] == 0)]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
6              7         0       1                   McCarthy, Mr. Timothy J   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch           Ticket     Fare Cabin Embarked  
0      male  22.0      1      0        A/5 21171   7.2500   NaN        S  
4      male  35.0      0      0           373450   8.0500   NaN        S  
5      male   NaN      0      0           330877   8.4583   NaN        Q  
6      male  54.0      0      0            17463  51.8625   E46        S  
7      male   2.0      3      1           349909  21.0750   NaN        S  
..      ...   ...    ...    ...              ...      ...   ...      ...  
884    male  25.0      0      0  SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5           382652  29.1250   NaN        Q  
886    male  27.0      0      0           211536  13.0000   NaN        S  
888  female   NaN      1      2       W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0           370376   7.7500   NaN        Q  

[576 rows x 12 columns]

## Pandas untuk Data Cleaning


### Nilai Kosong

**isna()** Akan mengembalikan **True** jika sel bernilai **null/Nan**


In [40]:
data.isna()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

In [131]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [133]:
# sum() akan menampilkan banyak null tiap kolom
null_per_column = data.isna().sum()
null_per_column

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

### Membersihkan Nilai Kosong


In [132]:
data.dropna(inplace=True)
data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

### Data Duplikat

**duplicated()** mengembalikan **True** jika baris terduplikasi


In [137]:
data.duplicated().sum()

0

### Membersihkan Data Duplikat


In [44]:
data.drop_duplicates(inplace=True)
data.duplicated().sum()

0

### Menghapus Baris & Kolom


In [148]:
copy_data = data.copy()
copy_data.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S

**labels**

- _single label or list-like_: Index or column labels to drop. A tuple will be used as a single label and not treated as a list-like.

**axis**

- _{0 or 'index', 1 or 'columns'}_, default 0: Whether to drop labels from the index (0 or 'index') or columns (1 or 'columns').

**index**

- _single label or list-like_: Alternative to specifying axis (labels, axis=0 is equivalent to index=labels).

**columns**

- _single label or list-like_: Alternative to specifying axis (labels, axis=1 is equivalent to columns=labels).


In [149]:
# Menghapus kolom Name, Sex, Age, SibSp
copy_data.drop(labels=['Name', 'Sex'], axis=1, inplace=True)
copy_data = copy_data.drop(columns=['Age', 'SibSp'])


# Menghapus baris 2 dan 4
copy_data.drop(labels=[6, 10], axis=0, inplace=True)
copy_data.drop(index=[1, 3], inplace=True)
copy_data

PassengerId  Survived  Pclass  Parch    Ticket      Fare        Cabin  \
11            12         1       1      0    113783   26.5500         C103   
21            22         1       2      0    248698   13.0000          D56   
23            24         1       1      0    113788   35.5000           A6   
27            28         0       1      2     19950  263.0000  C23 C25 C27   
52            53         1       1      0  PC 17572   76.7292          D33   
..           ...       ...     ...    ...       ...       ...          ...   
871          872         1       1      1     11751   52.5542          D35   
872          873         0       1      0       695    5.0000  B51 B53 B55   
879          880         1       1      1     11767   83.1583          C50   
887          888         1       1      0    112053   30.0000          B42   
889          890         1       1      0    111369   30.0000         C148   

    Embarked  
11         S  
21         S  
23         S  
27         S  
52         C  
..       ...  
871        S  
872        S  
879        C  
887        S  
889        C  

[179 rows x 8 columns]

## Supplementary Material


In [168]:
import pandas as pd

data_pilpres = {
    'Nama': ["Aice", "Pororo", "Genji", "Aice", "Pororo", "Genji", "Aice", "Pororo", "Genji"],
    'Lokasi TPS': ["Jatim", "Jatim", "Jabar", "Jabar", "Jabar", "Jatim", "Jatim", "Jabar", "Jatim"],
    'Suara Sah': [20, 30, 10, 25, 60, 15, 10, 20, 5],
    'Suara Tidak Sah': [0, 2, 1, 1, 5, 2, 0, 1, 0]
}
data_pilpres_df = pd.DataFrame(data_pilpres)
data_pilpres_df

Nama Lokasi TPS  Suara Sah  Suara Tidak Sah
0    Aice      Jatim         20                0
1  Pororo      Jatim         30                2
2   Genji      Jabar         10                1
3    Aice      Jabar         25                1
4  Pororo      Jabar         60                5
5   Genji      Jatim         15                2
6    Aice      Jatim         10                0
7  Pororo      Jabar         20                1
8   Genji      Jatim          5                0

### Sorting Values


In [157]:
data_pilpres_df.sort_values(by='Suara Sah', ascending=False)

Nama Lokasi TPS  Suara Sah  Suara Tidak Sah
4  Pororo      Jabar         60                5
1  Pororo      Jatim         30                2
3    Aice      Jabar         25                1
0    Aice      Jatim         20                0
7  Pororo      Jabar         20                1
5   Genji      Jatim         15                2
2   Genji      Jabar         10                1
6    Aice      Jatim         10                0
8   Genji      Jatim          5                0

In [158]:
data_pilpres_df.sort_values(by=['Suara Sah', 'Suara Tidak Sah'], ascending=False)

Nama Lokasi TPS  Suara Sah  Suara Tidak Sah
4  Pororo      Jabar         60                5
1  Pororo      Jatim         30                2
3    Aice      Jabar         25                1
7  Pororo      Jabar         20                1
0    Aice      Jatim         20                0
5   Genji      Jatim         15                2
2   Genji      Jabar         10                1
6    Aice      Jatim         10                0
8   Genji      Jatim          5                0

### GroupBy & Aggregation

**Group by** adalah operasi yang memungkinkan Anda untuk mengelompokkan baris data berdasarkan nilai pada satu atau beberapa kolom tertentu.

**Aggregation** adalah proses menggabungkan beberapa nilai menjadi satu nilai tunggal. Dalam konteks group by, aggregation sering digunakan untuk menghitung statistik ringkasan atau menghasilkan ringkasan data lainnya untuk setiap kelompok yang dihasilkan dari operasi group by


#### GroupBy Single Columns


In [159]:
data_pilpres_df

Nama Lokasi TPS  Suara Sah  Suara Tidak Sah
0    Aice      Jatim         20                0
1  Pororo      Jatim         30                2
2   Genji      Jabar         10                1
3    Aice      Jabar         25                1
4  Pororo      Jabar         60                5
5   Genji      Jatim         15                2
6    Aice      Jatim         10                0
7  Pororo      Jabar         20                1
8   Genji      Jatim          5                0

In [164]:
# Groupby berdasarkan kolom 'Nama'
grouped_by_name = data_pilpres_df.groupby('Nama')

aggregated = grouped_by_name.agg({
    'Suara Sah': 'sum',
    'Suara Tidak Sah': 'mean'
})

print(aggregated)

        Suara Sah  Suara Tidak Sah
Nama                              
Aice           55         0.333333
Genji          30         1.000000
Pororo        110         2.666667


#### GroupBy Double Columns


In [52]:
data_pilpres_df

Nama Lokasi TPS  Suara Sah  Suara Tidak Sah
0    Aice      Jatim         20                0
1  Pororo      Jatim         30                2
2   Genji      Jabar         10                1
3    Aice      Jabar         25                1
4  Pororo      Jabar         60                5
5   Genji      Jatim         15                2
6    Aice      Jatim         10                0
7  Pororo      Jabar         20                1
8   Genji      Jatim          5                0

In [165]:
# Groupby berdasarkan kolom 'Nama'
grouped_by_name_tps = data_pilpres_df.groupby(['Nama', 'Lokasi TPS'])

aggregated = grouped_by_name_tps.agg({
    'Suara Sah': ['sum', 'mean', 'median', 'min', 'max'],
})

print(aggregated)

                  Suara Sah                     
                        sum  mean median min max
Nama   Lokasi TPS                               
Aice   Jabar             25  25.0   25.0  25  25
       Jatim             30  15.0   15.0  10  20
Genji  Jabar             10  10.0   10.0  10  10
       Jatim             20  10.0   10.0   5  15
Pororo Jabar             80  40.0   40.0  20  60
       Jatim             30  30.0   30.0  30  30


### Apply

Metode **.apply()** pada Pandas adalah sebuah fungsi yang digunakan untuk menerapkan fungsi kustom (_user-defined function_) pada baris atau kolom DataFrame.


In [169]:
data_pilpres_df

Nama Lokasi TPS  Suara Sah  Suara Tidak Sah
0    Aice      Jatim         20                0
1  Pororo      Jatim         30                2
2   Genji      Jabar         10                1
3    Aice      Jabar         25                1
4  Pororo      Jabar         60                5
5   Genji      Jatim         15                2
6    Aice      Jatim         10                0
7  Pororo      Jabar         20                1
8   Genji      Jatim          5                0

In [170]:
# Apply hanya pada sebuah kolom tertentu (Suara Sah)

def manipulate_data(x):
    return x * 10


data_pilpres_df['Suara Sah'] = data_pilpres_df['Suara Sah'].apply(manipulate_data)
data_pilpres_df

Nama Lokasi TPS  Suara Sah  Suara Tidak Sah
0    Aice      Jatim        200                0
1  Pororo      Jatim        300                2
2   Genji      Jabar        100                1
3    Aice      Jabar        250                1
4  Pororo      Jabar        600                5
5   Genji      Jatim        150                2
6    Aice      Jatim        100                0
7  Pororo      Jabar        200                1
8   Genji      Jatim         50                0

In [173]:
# Apply pada beberapa kolom (Suara Sah dan tidak sah)

def totaling_suara(row):
    return row['Suara Sah'] + row['Suara Tidak Sah']


data_pilpres_df['Total Suara'] = data_pilpres_df.apply(totaling_suara, axis=1)
data_pilpres_df

Nama Lokasi TPS  Suara Sah  Suara Tidak Sah  Total Suara
0    Aice      Jatim        200                0          200
1  Pororo      Jatim        300                2          302
2   Genji      Jabar        100                1          101
3    Aice      Jabar        250                1          251
4  Pororo      Jabar        600                5          605
5   Genji      Jatim        150                2          152
6    Aice      Jatim        100                0          100
7  Pororo      Jabar        200                1          201
8   Genji      Jatim         50                0           50

### Saving DataFrame

**DataFrame** yang sudah diolah dapat disimpan kembali dalam bentuk file dengan format terntentu.


In [174]:
data_pilpres_df.to_csv("data_pilpres.csv", index=False)
data_pilpres_df.to("data_pilpres.csv", index=False)

# QnA 🙏


In [175]:
import pandas as pd

data_pilpres = {
    'Nama': ["Aice", "Pororo", "Genji", "Aice", "Pororo", "Genji", "Aice", "Pororo", "Genji"],
    'Lokasi TPS': ["Jatim", "Jatim", "Jabar", "Jabar", "Jabar", "Jatim", "Jatim", "Jabar", "Jatim"],
    'Suara Sah': [20, 30, 10, 25, 60, 15, 10, 20, 5],
    'Suara Tidak Sah': [0, 2, 1, 1, 5, 2, 0, 1, 0]
}
data_pilpres_df = pd.DataFrame(data_pilpres)
data_pilpres_df

Nama Lokasi TPS  Suara Sah  Suara Tidak Sah
0    Aice      Jatim         20                0
1  Pororo      Jatim         30                2
2   Genji      Jabar         10                1
3    Aice      Jabar         25                1
4  Pororo      Jabar         60                5
5   Genji      Jatim         15                2
6    Aice      Jatim         10                0
7  Pororo      Jabar         20                1
8   Genji      Jatim          5                0

In [ ]:
# Merge, Concat, Join Outer, Inner Join

In [176]:
data['Name']

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
6                                McCarthy, Mr. Timothy J
10                       Sandstrom, Miss. Marguerite Rut
11                              Bonnell, Miss. Elizabeth
                             ...                        
871     Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
872                             Carlsson, Mr. Frans Olof
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
887                         Graham, Miss. Margaret Edith
889                                Behr, Mr. Karl Howell
Name: Name, Length: 183, dtype: object